theme/dt-theme/dark/table.less
theme/dt-theme/default/button.less
theme/dt-theme/default/table.less

修复 issues 24 提出的bug。问题原因：样式选择器的权重导致的样式覆盖

feat: modify issues 24 in button.less

---

components/table/demo/fixBase.md
components/table/demo/fixFooter.md
components/table/demo/size.md
theme/dt-theme/dark/table.less
theme/dt-theme/default/form.less
theme/dt-theme/default/table.less
theme/dt-theme/dt-common/form.less
theme/dt-theme/dt-common/table.less

Feat 1.1.5 36

---

components/empty/demo/config-provider.md
components/empty/demo/light.md
components/form/demo/light.md
components/timepicker/demo/light.md
theme/dt-theme/default/card.less
theme/dt-theme/default/index.less
theme/static/common.less
theme/static/header.less

- 修复第一部分升级后的样式污染问题
1. 修复以下组件样式问题
- Alert
- Button
- Calendar
- Card
- Datepicker
- Empty
2. 还原升级后顶部搜索框

Fixed the post-upgrade style bug in part 1

---

bisheng.config.js
components/form/demo/basic.md
components/form/demo/light.md
components/layout/demo/basic.md
components/layout/demo/projectSelect.md
components/layout/demo/sider.md
components/layout/demo/siderIconfont.md
components/steps/demo/basic.md
theme/dt-theme/dark/layout.less
theme/dt-theme/dark/table.less
theme/dt-theme/default/layout.less
theme/dt-theme/default/table.less
theme/dt-theme/dt-common/layout.less
theme/template/Layout/Header.jsx

Feat 2.0.0 zhaoge

---

components/step/demo/icon.md
components/steps/demo/basic.md
components/tab/demo/icon.md
components/table/demo/expand.md
components/tree/demo/line.md
components/upload/demo/avatar.md
components/upload/demo/basic.md
components/upload/demo/drag.md
components/upload/demo/picture-card.md
theme/dt-theme/dark/form.less
theme/dt-theme/default/form.less
theme/dt-theme/dt-common/form.less
theme/dt-theme/dt-common/table.less
theme/static/common.less
theme/template/Content/MainContent.jsx

feat: update v4.0 style

---

components/checkbox/demo/basic.md
components/form/demo/basic.md
components/radio/demo/basic.md
components/transfer/demo/basic.md
components/transfer/index.zh-CN.md
theme/dt-theme/default/collapse.less
theme/dt-theme/default/datepicker.less
theme/dt-theme/default/descriptions.less
theme/dt-theme/default/index.less
theme/dt-theme/default/modal.less
theme/dt-theme/default/notice.less
theme/dt-theme/default/transfer.less
theme/dt-theme/default/tree.less
theme/dt-theme/dt-common/form.less
theme/dt-theme/dt-common/notice.less

fix issues:
- #106 
- #107 
- #109 
- #112 
- #116 
- #117 
- #111 
- #113 
- #115 
- #124

Beta 2.0.0 xigua

---

components/popover/demo/position.md
components/popover/demo/tipstyle.md
theme/dt-theme/default/cascader.less

Fix beta 2.0.0 beier

---

theme/dt-theme/default/cascader.less
theme/dt-theme/default/index.less
theme/dt-theme/default/modal.less
theme/dt-theme/default/notice.less
theme/dt-theme/default/table.less
theme/dt-theme/default/treeselect.less
theme/dt-theme/index.less

变更如下：
1.  #93 
2. #97 
3. #106 
4. #107 
5. #109

Beta 2.0.0 zhaoge

---

theme/dt-theme/default/input.less

补充修复Input hover时的color变化：
1. #130

style: update Input's color

---

theme/template/Content/ComponentDoc.jsx
theme/template/Content/Demo.jsx

fix: icon import from @ant-design/icons

---

theme/dt-theme/dt-common/layout.less

修复 [UI5.0：dt-common问题](http://gitlab.prod.dtstack.cn/dt-insight-front/dt-insight-studio/issues/65)，第三个按钮是 hover 效果，和设计确认了

style: dt-common .menu-right, .menu-item

---

theme/dt-theme/default/cascader.less
theme/dt-theme/index.less

变更：
1、dt-theme/index.less引入cascader.less文件修改select的默认样式
2、增加`opacity:0`的样式，在选择select下拉某项后隐藏光标
关联issue：
#162

Beta 2.0.0 select

---

components/table/demo/basic.md
components/table/demo/fixBase.md
components/table/demo/fixFooter.md
components/table/demo/scroll.md
components/table/demo/selectAndDeal.md
theme/dt-theme/default/table.less
theme/dt-theme/dt-common/table.less
theme/dt-theme/index.less

Modify：
1、theme/dt-theme/index.less引入input.less文件修改antd input的默认样式
2、去除table中a标签的边距，根据UI5.0设计稿增加分割线的样式，同时修改table demon文档例子
3、修改table border的颜色样式
#161 #156 #154

Beta 2.0.0 input table

---

theme/dt-theme/dt-common/layout.less

Modify:
1、根据UI5.0设计稿优化siderbar样式
resolved #157

style: optimized dt-common siderbar style

---

theme/dt-theme/dt-common/layout.less

Modify:
1、根据UI5.0设计稿优化header菜单样式
resolved #160

style: optimized dt-common layout header style

---

theme/dt-theme/default/modal.less
theme/dt-theme/dt-common/modal.less
theme/dt-theme/index.less

Modify:
1、根据UI5.0优化二次确认弹窗样式
2、在dt-common的index文件引入抽屉的样式
resolved #153
resolved #169

Beta 2.0.0 drawer modal

---

theme/dt-theme/default/layout.less
theme/dt-theme/dt-common/layout.less

Modify:
1、根据UI5.0规范和UI确认优化header和sider样式

style: optimized header and sider style

---

theme/dt-theme/default/drawer.less
theme/dt-theme/dt-common/layout.less

链接：http://gitlab.prod.dtstack.cn/dt-insight-front/dt-insight-studio/issues/65  
问题：截图的第一个点

style: #65 tag header space between

---

theme/dt-theme/default/dropdown.less
theme/dt-theme/default/index.less
theme/dt-theme/index.less

Modify:
1、根据UI5.0优化`dropdown button`样式
resolved #176

fix: add dropdown button style

---

components/button/demo/danger.md
theme/dt-theme/default/button.less

Modify:
1、修改danger button文档
2、根据UI5.0优化按钮样式，删除冗余代码
resolved #174

Optimized  Button style

---

package.json
theme/template/Layout/index.jsx
yarn.lock

feat: some dependencies

---

theme/dt-theme/default/pagination.less
theme/dt-theme/default/table.less
theme/dt-theme/dt-common/table.less

Modify:
1、优化pagination样式
2、修复`dt-table-fixed-contain-footer`导致的页脚未固定的问题
resolved #159 
resolved #151 
resolved #150

Beta 2.0.0 table pagination

---

theme/dt-theme/default/button.less
theme/dt-theme/dt-common/layout.less

Modify:
1、优化ant button link类型禁用状态样式
2、移除 `ant-menu-title-content`样式，修复以下问题

Beta 2.0.0 layout link

---

components/datepicker/demo/size.md

docs: #182

---

theme/dt-theme/default/cascader.less

style: select tag item height

---

theme/dt-theme/default/input.less

#190 
校验失败后再次 focus 会有浅红色边框，使用 antd 默认效果

style: form validate input focus border color

---

theme/dt-theme/dt-common/layout.less

style: menu height

---

theme/dt-theme/default/button.less

style: button link css

---

theme/dt-theme/default/pagination.less

Modify:
1、设置pagination组件内部垂直居中
Relation:
resolved #185

fix: set pagination vertical

---

theme/dt-theme/default/form.less

Modify:
1、根据UI5.0设计稿优化错误提示信息样式
Relation:
Resolved #152

style: optimized form item explain error style

---

theme/dt-theme/default/cascader.less

Modify:
1、修改select字体和下拉菜单字体的颜色
Relation：
Resolved #202

style: modify ant select text color

---

bisheng.config.js
package.json
yarn.lock

support dynamic resolve via dynamic-resolve-webpack-plugin

feat: support dynamic resolve via dynamic-resolve-webpack-plugin

---

theme/dt-theme/default/table.less

Modify:
1、去掉空值的hover颜色效果以及底线
Relation:
Resolved #216

style: optimized table empty style

---

theme/dt-theme/default/table.less
theme/dt-theme/dt-common/table.less

Modify:
1、优化表格行高，43内容+1border
2、优化嵌套子表格式样式错乱的问题
Relation:
#147

style: optimied table height and children table style

---

components/steps/demo/basic.md
components/steps/demo/card.md
components/steps/index.zh-CN.md
theme/dt-theme/default/steps.less

feat: add new className for steps

---

theme/dt-theme/default/table.less

Modify:
1、嵌套子表格时，扩展按钮居中对齐
Relation:
resolved #225

style: #225 append cell center

---

theme/dt-theme/default/button.less
theme/dt-theme/default/table.less

Modify:
1、修改button的line-height解决不同尺寸的按钮文字未居中的问题
2、根据UI5.0优化table筛选下拉的按钮样式问题
Relation:
#186

style: #186 optimized table sort buttons style

---

theme/dt-theme/dt-common/layout.less

style: nav background color

---

theme/dt-theme/default/pagination.less

style: pagination height

---

theme/dt-theme/dt-common/layout.less

Modify:
1、调整左侧菜单样式和与产品logo的间距
Relation:
#238

style: optimized dt-common header style #238

---

theme/dt-theme/default/datepicker.less

style: datepicker height

---

theme/dt-theme/default/table.less

Modify:
1、去除ant-pagination height导致的未居中问题
Relation:
#246

style: #246 removed ant-pagination height

---

theme/dt-theme/default/breadcrumb.less

Modify:
1、修改面包屑的文字大小和行高
Relation:
#250

style: optimized breadcrumb #250

---

theme/dt-theme/default/table.less

Modify:
1、优化dt-table-fixed-base中border的颜色
Relation:
#254

style: optimized dt-table-fixed-base border color #254

---

theme/dt-theme/default/table.less

Modify:
1、修改table hover的背景色
Relation:
#260

feat: modify table hover background color #260

---

theme/dt-theme/default/descriptions.less

Modify:
1、根据UI5.0设计稿调整编剧和高度
Relation:
#257

feat: optimized Descriptions #257

---

components/table/demo/empty.md
components/treeselect/demo/checkbox.md
components/treeselect/demo/light.md
components/treeselect/demo/shadow.md
theme/dt-theme/default/popover.less
theme/dt-theme/default/tab.less
theme/dt-theme/default/table.less
theme/dt-theme/default/treeselect.less

#241 5.0 Tabs
#244 Popconfirm 样式不对 
#248 TreeSelect checkbox 尚未居中 同步增加了一个示例
#249 Table empty 居中 同步增加了一个示例

Beta 2.0.0 issue

---

components/input-number/demo/basic.md
components/input-number/demo/size.md
components/input-number/index.zh-CN.md
theme/dt-theme/default/index.less
theme/dt-theme/default/input-number.less
theme/dt-theme/dt-common/form.less

Modify:
1、根据UI5.0修改`InputNumber`组件样式
2、增加相应的文档
Relation:
#289

Beta 2.0.0 289

---

theme/dt-theme/default/button.less
theme/dt-theme/default/popover.less

Modify:
1、删除冗余代码对`Popconfirm`中按钮的影响
Relation:
#292

style: optimized ant small button style

---

theme/dt-theme/dt-common/notice.less

style: notification style

---

theme/dt-theme/default/radio.less
theme/dt-theme/default/table.less

#296 UI 5.0--Radio【文案和radio不对齐问题】
#284 UI 5.0 表格空状态占位
#286 UI 5.0--Table空状态

Beta-2.0.0-issue

---

theme/dt-theme/default/input.less
theme/dt-theme/default/select.less

Modify:
1、修复input高度问题导致的样式错乱
2、优化多选select的样式
Relation:
#324 #287

Beta 2.0.0 324 287

---

components/table/demo/basic.md
components/table/demo/edit-cell.md
theme/dt-theme/default/form.less
theme/dt-theme/default/select.less
theme/dt-theme/default/table.less

Modify:
1、优化水平表单标题个内容的距离，antd默认值符合设计规范
2、增加select下拉菜单上下8px的边距
3、优化`Table`样式去掉顶部圆角
4、优化table文档，增加可编辑表格例子
Relation:
#262 #329

Beta 2.0.0 262 329

---

theme/dt-theme/default/checkbox.less
theme/dt-theme/default/notice.less
theme/dt-theme/default/select.less

#263 
#302 
1. 多选下拉框tag高度修复，
2. checkboxgroup中间距问题
3. alert当标题为多行时 图标与第一行对其

style: multiple select height & alert icon align

---

theme/dt-theme/default/menu.less

style: header dropdown submenu hide

---

theme/dt-theme/default/cascader.less
theme/dt-theme/dt-common/layout.less

style: #349 cascader padding

---

theme/dt-theme/default/popover.less
theme/dt-theme/default/select.less

Beta 2.0.0 347

---

components/transfer/demo/basic.md
theme/dt-theme/default/descriptions.less
theme/dt-theme/default/table.less
theme/dt-theme/default/transfer.less
theme/dt-theme/default/upload.less

Modify:
1、优化upload禁用样式 #400 
2、优化descriptions标题颜色，去除冗余的颜色声明 #405 
3、去除可拖拽表格选框后面的线 #399 
4、根据UI5.0优化穿梭框样式 #397

Feat 2.0.0 issues

---

theme/dt-theme/default/breadcrumb.less

Modify:
1、优化breadcrumb样式separator样式

feat: optimized breadcrumb separator

---

components/table/demo/basic.md
components/table/index.zh-CN.md
theme/dt-theme/default/table.less

Modify:
1、增加table换行类名`dt-table-multi-line` #406 #453 
2、补充对应的文档

feat: add dt-table-multi-line custom className

---

components/input-number/demo/addon.md
theme/dt-theme/default/input-number.less

feat: #471 ant-input-number-group-addon

---

components/table/demo/edit-cell.md
components/table/demo/expand-checkbox.md
components/table/demo/numberRight.md
components/table/demo/resizable.md
theme/dt-theme/default/table.less

1. #479 
- 代码由 #226 的 PR 引入，issue 是  #225
- theme 新增示例  
- 离线修改后没有 #225  的问题，#479 的问题也解决了

fix: #479 table ant-table-cell-with-append

---

components/input/demo/search-input.md
components/input/index.zh-CN.md
theme/dt-theme/default/input.less

Modify:
- 增加`dt-input-search-group-shadow`自定义类名和例子
- 增加`dt-input-search-external`自定义类名和例子
- 搜索按钮去除底色 #490

feat: add Search lead example #490

---

components/button/demo/loading.md
theme/dt-theme/const.less
theme/dt-theme/const.scss
theme/dt-theme/default/button.less
theme/dt-theme/default/steps.less
theme/dt-theme/default/table.less

1. #512 
2. #507 
3. #511 
4. #491

Feat 2.x all

---

components/pagination/demo/basic.md
components/pagination/demo/full.md
components/pagination/demo/size.md
components/pagination/index.zh-CN.md
components/table/demo/basic.md
components/table/demo/expand.md
components/table/demo/fixBase.md
components/table/demo/fixFooter.md
components/table/demo/numberRight.md
components/table/demo/scroll.md
components/table/demo/selectAndDeal.md
components/transfer/demo/basic.md
theme/dt-theme/default/pagination.less

Modify:
- 优化分页总条数样式
- 增加le类名dt-pagination-totalCount
Relation:
#516

fix: #516 add dt-pagination-totalCount class

---

components/table/demo/fixBase.md
theme/dt-theme/default/table.less

Modify:
- 修复水平滚动empty table 样式
Issue:
- #518 
Display:

fix: #518 horizontal scroll empty table style

---

components/table/demo/edit-cell.md
components/table/demo/emptyScrollTable.md
components/table/demo/expand.md
components/table/demo/filter-sort.md
components/table/demo/fixBase.md
components/table/demo/fixFooter.md
components/table/demo/numberRight.md
components/table/demo/resizable.md
components/table/demo/scroll.md
components/table/demo/selectAndDeal.md
components/table/demo/size.md

Modify:
- 增加水平滚动空状态Table示例
Issue:
- #520 
Display:

feat: #520 add empty scroll table doc

---

theme/dt-theme/default/layout.less

style: #525 dropdown item hover background-color

---

components/modal/demo/confirm.md
theme/dt-theme/default/modal.less

fix: #527 modal danger btn hover

---

theme/dt-theme/default/popover.less

style: #529 popover box-shadow

---

components/tag/demo/color.md
components/tag/demo/icon.md
theme/dt-theme/default/tag.less

1. #534 
less each 循环，覆写 antd 的 tag color 样式，具体颜色值采用的是 antd4 的 tag color

fix: #534 tag color

---

components/alert/demo/icon.md
components/button/demo/danger.md
theme/dt-theme/default/alert.less
theme/dt-theme/default/button.less
theme/dt-theme/default/form.less
theme/dt-theme/default/input.less
theme/dt-theme/default/modal.less
theme/dt-theme/default/notice.less

1. #550 
2. #549 
3. #547
4. #546 
5. #545 
预览地址：https://liuxy0551.github.io/ant-design-dtinsight-theme/components/alert-cn/

Fix issues

---

components/table/demo/numberRight.md
components/table/demo/selectAndDeal.md
components/table/demo/selected.md

docs: #552 table footer align-items center

---

theme/dt-theme/default/tab.less

fix(tabs): hover disable not show active

---

theme/dt-theme/dark/tree.less
theme/dt-theme/default/radio.less
theme/dt-theme/default/tree.less
theme/dt-theme/default/treeselect.less

style: #560 #561

---

components/tab/demo/card.md
components/tab/demo/editable-card.md
components/tab/demo/light.md
components/tab/demo/sider-menu.md
components/tab/demo/slide-vertical.md
components/tab/index.zh-CN.md
theme/dt-theme/default/tab.less
theme/static/header.less
theme/template/NotFound.jsx

style: #563 tabs

---

theme/dt-theme/dark/steps.less
theme/dt-theme/default/steps.less

fix(steps): #566, update steps footer btns gap to 12px

---

theme/dt-theme/default/tab.less

style: #563 anticon margin
